/*

 MAP.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 40 x 40
   Tile set      : Z:\home\jon\Documents\castle-of-the-magic-dingdong\res\tile_set2.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define mapWidth 120
#define mapHeight 120
#define mapBank 0

extern unsigned char map[];

/* End of MAP.H */
