/*

 MAP40.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 40 x 40
   Tile set      : Z:\home\jon\Documents\castle-of-the-magic-dingdong\res\tile_set40.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define map_part_1Width 40
#define map_part_1Height 40
#define map_part_1Bank 0

extern unsigned char map_part_1[];

/* End of MAP40.H */
