/*

 TILES.C

 Tile Source File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 1

  Palette colors       : None.
  SGB Palette          : None.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

/* Start of tile array. */
unsigned char tiles[] =
{
  0x7F,0x7F,0x80,0x80,0x80,0x80,0xC0,0xC0,
  0x7F,0x7F,0x08,0x08,0x08,0x08,0x08,0x08,
  0x00,0x00,0x00,0x00,0x28,0x28,0x10,0x10,
  0x28,0x28,0x04,0x04,0x00,0x00,0x00,0x00
};

/* End of TILES.C */
